version: "3.7"
services:
  app:
    container_name: app
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./app/:/var/www/html/"
    ports:
      - "8080:80"
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    restart: always
    env_file:
      - .db.env
    volumes: 
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  dbdata: