version: "3.7"
services:
  app:
    container_name: app
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./app/:/var/www/html/"
    ports:
      - "8080:80"
  localhost:
    image: mysql/mysql-server:8.0
    container_name: dbapp
    restart: always
    env_file:
      - .db.env
    volumes: 
      - ./db/init:/docker-entrypoint-initdb.d
      # - dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
  # wikisql:
  #   image: mysql/mysql-server:8.0
  #   container_name: wikisql
  #   restart: always
  #   env_file:
  #     - .mediawiki.env
  #   volumes: 
  #     - wikidata:/var/lib/mysql
  #   ports:
  #     - "3309:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - localhost
    environment:
      PMA_HOST: localhost
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  dbdata:
  wikidata: